/*
 * Copyright(c) 2006 to 2019 ADLINK Technology Limited and others
 * Copyright(c) 2019 Jeroen Koekkoek
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */
#ifndef IDL_H
#define IDL_H

#include "dds/ddsrt/attributes.h"
#include "dds/ddsrt/retcode.h"
#include "dds/ddsts/typetree.h"

/* yyscan_t is an opaque pointer, a typedef is required here to break a
   circular dependency introduced with bison 2.6 (normally a typedef is
   generated by flex). the define is required to disable the typedef in flex
   generated code */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void *yyscan_t;
#endif

typedef struct idl_file idl_file_t;

struct idl_file {
  idl_file_t *next;
  char *name;
};

typedef struct idl_parser idl_parser_t;

struct idl_parser {
  yyscan_t scanner;
  idl_file_t *files;
};

dds_return_t idl_parse_file(const char *file, ddsts_type_t **ref_root_type);

dds_return_t idl_parse_string(const char *str, ddsts_type_t **ref_root_type);

#endif /* IDL_H */

