// Copyright(c) 2023 ZettaScale Technology and others
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
// v. 1.0 which is available at
// http://www.eclipse.org/org/documents/edl-v10.php.
//
// SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause

@final
struct dsub1 {
    int32 m_int32;
};

@final
struct dsubsub1 {
    boolean m_bool;
};

@final
struct dsubsub2 {
    boolean m_bool;
};

@final
struct dsub2 {
    dsubsub1 m_subsub1;
    dsubsub2 m_subsub2;
};

typedef dsubsub1 dalias;

@final
union dunion switch (int32) {
    case 9:
    case 10:
        @id(100) double um_f;
    case 15:
    case 16:
        dsub1 um_sub1;
};

enum denum { DE1, DE2 };

@final
struct dstruct {
    boolean m_bool;
    sequence<dsub2> m_seq;
    dsub2 m_arr[10];
    dsub1 m_sub1;
    dsub2 m_sub2;
    dsubsub2 m_subsub2;
    dalias m_alias;
    dunion m_union;
    denum m_enum;
};
