// Copyright(c) 2023 ZettaScale Technology, Incorporated
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
// v. 1.0 which is available at
// http://www.eclipse.org/org/documents/edl-v10.php.
//
// SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause

struct SC_Model {
  octet a,b,c;
};

struct NSC_Model {
  string a,b,c;
};

@nested
struct PsmxType1xy {
  long x;
  octet y;
};

// A memcpy-able type where fields are laid differently in C
// and CDR:
// offset
//         C   CDR
// x.x     0   0
// x.y     4   4
// x.z     8   5
//
// size   12   6
struct PsmxType1 {
  PsmxType1xy xy;
  octet z;
};

struct PsmxKeySupportCheck {
  @key long k;
};

struct PsmxLoanTest0 {
  PsmxType1xy xy;
  @key octet z;
};

struct PsmxLoanTest1 {
  PsmxType1xy xy;
  @key octet z;
  string str;
};

struct PsmxLoanTest2 {
  PsmxType1xy xy;
  @key octet z;
  @key string str;
};
