// Copyright(c) 2006 to 2022 ZettaScale Technology and others
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
// v. 1.0 which is available at
// http://www.eclipse.org/org/documents/edl-v10.php.
//
// SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause

module XSpaceEnum {
  @final enum enum_f { F1, F2, F3 };
  @appendable enum enum_a { A1, A2, A3 };

  @final struct rd1 { enum_f f1; };
  @final struct wr1_1 { enum_f f1; };
  @final struct wr1_2 { enum_a f1; };

  @final struct rd2 { enum_a f1; };
  @final struct wr2_1 { enum_a f1; };
  @final struct wr2_2 { enum_f f1; };
};

module XSpaceEnumPlus {
  @final enum enum_f_plus { F1, F2, F3, F4 };
  @appendable enum enum_a_plus { A1, A2, A3, A4 };

  @final struct wr1_3 { enum_f_plus f1; };
  @final struct wr2_3 { enum_a_plus f1; };
};

module XSpaceEnumMin {
  @final enum enum_f_min { F1, F2 };
  @appendable enum enum_a_min { A1, A2 };

  @final struct wr1_4 { enum_f_min f1; };
  @final struct wr2_4 { enum_a_min f1; };
};

module XSpaceEnumLabel {
  @final enum enum_f_label { F1, FFF2, F3 };
  @appendable enum enum_a_label { A1, AAA2, A3 };

  @final struct wr1_5 { enum_f_label f1; };
  @final struct wr2_5 { enum_a_label f1; };
};

module XSpaceBitmask {
  @final @bit_bound(8) bitmask bm_f { BMF0, BMF1 };
  @appendable @bit_bound(8) bitmask bm_a { BMA0, BMA1 };

  @final @bit_bound(8) bitmask bm_f_plus { BMFP0, BMFP1, BMFP2 };
  @appendable @bit_bound(8) bitmask bm_a_plus { BMAP0, BMAP1, BMAP2 };

  @final @bit_bound(8) bitmask bm_f_min { BMFM0 };
  @appendable @bit_bound(8) bitmask bm_a_min { BMAM0 };

  @final @bit_bound(16) bitmask bm_f_wide { BMFW0, BMFW1 };
  @appendable @bit_bound(16) bitmask bm_a_wide { BMAW0, BMAW1 };

  @final struct rd_f { bm_f f1; };
  @final struct rd_a { bm_a f1; };

  @final struct wr_f { bm_f f1; };
  @final struct wr_a { bm_a f1; };
  @final struct wr_f_plus { bm_f_plus f1; };
  @final struct wr_a_plus { bm_a_plus f1; };
  @final struct wr_f_min { bm_f_min f1; };
  @final struct wr_a_min { bm_a_min f1; };
  @final struct wr_f_wide { bm_f_wide f1; };
  @final struct wr_a_wide { bm_a_wide f1; };
};
